### ISSUE TITLE
Sonarcloud integration broken

### ISSUE THREAD

**Issue by pathob** [aservo/confapi-commons#153]
Somewhere between [14 March](https://github.com/aservo/confapi-commons/actions/runs/8283404536) and [yesterday](https://github.com/aservo/confapi-commons/actions/runs/9092970891) the Sonarcloud integration stopped working.

Since I don't have the necessary rights on both, Github and Sonarcloud, I would like to ask the ASERVO maintainers to fix it...

**Comment by pathob** [comment]
@LouisZschaler @brettaufheber This prevents us from building an important bugfix for ConfAPI for Crowd

**Comment by brettaufheber** [comment]
To be honest, I am surprised that the static code analysis has ever worked for this project. The crucial attributes to identify the organization and project are missing.

            <properties>
                <sonar.projectKey>aservo_confapi-commons</sonar.projectKey>
                <sonar.organization>800c9135c81800959e51375f6594c91a1f757be9bbbc14d311783a4f75c501ec7807da061e787a9ea89433eb1cf2d6088b664332abd6a411ca5b44e811e97a23</sonar.organization>
                <sonar.host.url>https://sonarcloud.io</sonar.host.url>
            </properties>
